rvm:
  # - 1.8.7
  # - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby-19mode
  # - rbx
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

install: bundle install --without travis_excluded --jobs=3 --retry=3

branches:
  except:
    - /^v[0-9]/