# use container-based infrastructure
sudo: false

rvm:
  - 1.9.3
  - 2.1.7
  - 2.2.3
  - 2.3.0
  - jruby-19mode
  # - rbx
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  except:
    - /^v[0-9]/

notifications:
  email:
    on_failure: change
    on_success: never
